module.exports = (sequelize, Sequelize) => {
  const Comment = sequelize.define('comment', {
    //  Primary key id automatically generated by sequelize
    content: {
      type: Sequelize.STRING,
      allowNull: false,
    },
  })

  return Comment
}
