module.exports = (sequelize, Sequelize) => {
  const Post = sequelize.define('post', {
    // Primary key id automatically generated by sequelize
    // id: {
    //   type: Sequelize.INTEGER,
    //   autoIncrement: true,
    //   primaryKey: true,
    //   allowNull: false,
    // },
    content: {
      type: Sequelize.STRING,
      allowNull: false,
    },
    imageUrl: {
      type: Sequelize.STRING,
      allowNull: true,
    },
    like: {
      type: Sequelize.INTEGER,
      allowNull: true,
    },
  })

  return Post
}
